-- DataOmni 示例 schema：一套专门用来观察 ER 关系图的表。
--
-- 这套结构刻意覆盖了几种在图上长得不一样的情况：
--   * 一条链：customers → orders → order_items
--   * 一个分叉：order_items 同时指向 orders 和 products
--   * 自引用：categories.parent_id → categories.id（图上是一个回到自己的框）
--   * 复合外键：inventory (warehouse_code, product_id) → warehouses / products
--   * 孤立的表：audit_log、schema_migrations、feature_flags——它们一条外键
--     都没有，正是用来确认「没有关联的表也画出来」这件事
--
-- PostgreSQL 方言。MySQL 版本见 sample-schema.sql。
-- 用法（PostgreSQL）——建库要单独一步，CREATE DATABASE 不能在事务里跑：
--   createdb -h HOST -U USER dataomni_demo
--   psql -h HOST -U USER -d dataomni_demo -f examples/sample-schema.postgres.sql

-- 先按依赖的反序删，重复执行这个脚本才不会被外键挡住
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS warehouses;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS schema_migrations;
DROP TABLE IF EXISTS feature_flags;

CREATE TABLE regions (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(8) NOT NULL UNIQUE,
  name        VARCHAR(64) NOT NULL
);

CREATE TABLE customers (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id   INT NULL REFERENCES regions (id) ON DELETE SET NULL,
  name        VARCHAR(64) NOT NULL,
  email       VARCHAR(128) NULL UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 自引用：图上会画出一条从 parent_id 绕回 id 的线
CREATE TABLE categories (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id   INT NULL REFERENCES categories (id) ON DELETE CASCADE,
  name        VARCHAR(64) NOT NULL
);

CREATE TABLE products (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INT NULL REFERENCES categories (id) ON DELETE SET NULL,
  sku         VARCHAR(32) NOT NULL UNIQUE,
  name        VARCHAR(128) NOT NULL,
  price       NUMERIC(12, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE orders (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   INT NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
  status        VARCHAR(16) NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft', 'paid', 'shipped', 'cancelled')),
  total         NUMERIC(20, 4) NOT NULL DEFAULT 0.0000,
  placed_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_orders_customer ON orders (customer_id);

-- 分叉：同时指向 orders 与 products
CREATE TABLE order_items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  product_id  INT NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
  quantity    INT NOT NULL DEFAULT 1,
  unit_price  NUMERIC(12, 2) NOT NULL,
  CONSTRAINT ck_order_items_quantity CHECK (quantity > 0)
);

CREATE TABLE warehouses (
  code        VARCHAR(8) NOT NULL PRIMARY KEY,
  region_id   INT NULL REFERENCES regions (id) ON DELETE SET NULL,
  name        VARCHAR(64) NOT NULL
);

-- 复合主键 + 两条外键，其中一条的列顺序与声明顺序不同，
-- 正好用来看连线有没有接错列
CREATE TABLE inventory (
  product_id      INT NOT NULL,
  warehouse_code  VARCHAR(8) NOT NULL,
  quantity        INT NOT NULL DEFAULT 0,
  PRIMARY KEY (warehouse_code, product_id),
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id)
    REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_warehouse FOREIGN KEY (warehouse_code)
    REFERENCES warehouses (code) ON DELETE CASCADE
);

-- 下面三张一条外键都没有：图上应当照常出现，排在有关联的分组下面
CREATE TABLE audit_log (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor     VARCHAR(64) NULL,
  action    VARCHAR(64) NOT NULL,
  payload   JSONB NULL,
  logged_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE schema_migrations (
  version    VARCHAR(32) NOT NULL PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE feature_flags (
  name      VARCHAR(64) NOT NULL PRIMARY KEY,
  enabled   BOOLEAN NOT NULL DEFAULT false,
  note      TEXT NULL
);

-- 一点数据，方便顺手看表格视图
INSERT INTO regions (code, name) VALUES ('cn-east', '华东'), ('cn-north', '华北');
INSERT INTO categories (parent_id, name) VALUES (NULL, '全部');
INSERT INTO categories (parent_id, name) VALUES (1, '电子'), (1, '家居');
INSERT INTO customers (region_id, name, email) VALUES
  (1, '张伟', 'zhangwei@example.com'),
  (2, 'Ada Lovelace', 'ada@example.com');
INSERT INTO products (category_id, sku, name, price) VALUES
  (2, 'SKU-1001', '机械键盘', 499.00),
  (3, 'SKU-2001', '台灯', 129.50);
INSERT INTO warehouses (code, region_id, name) VALUES ('WH-E1', 1, '华东一仓');
INSERT INTO inventory (product_id, warehouse_code, quantity) VALUES (1, 'WH-E1', 25);
INSERT INTO orders (customer_id, status, total) VALUES (1, 'paid', 499.0000);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (1, 1, 1, 499.00);
INSERT INTO schema_migrations (version) VALUES ('20260101_init');
INSERT INTO feature_flags (name, enabled, note) VALUES ('er_diagram', true, '关系图');
