import type { CreatableDialect, SchemaDraft } from './schemaDraft';

/** 发给模型的一轮对话。界面上原样展开给人看：发出去的就是这些，没有别的 */
export interface DesignMessages {
  system: string;
  user: string;
}

const DIALECT_NAMES: Record<CreatableDialect, string> = {
  mysql: 'MySQL 8',
  postgresql: 'PostgreSQL',
  sqlite: 'SQLite',
  sqlserver: 'SQL Server',
  oracle: 'Oracle',
  duckdb: 'DuckDB'
};

/**
 * 自增在各家的写法。放进类型里是权宜：A0 实验里让模型自己选，PostgreSQL 有 7/30 写成了
 * `nextval('…_seq')` 而序列不存在；写死一种建得出来的，比让它猜强
 */
const AUTO_INCREMENT_HINT: Record<CreatableDialect, string> = {
  postgresql: '自增主键的 dataType 写 "bigint GENERATED ALWAYS AS IDENTITY"',
  mysql: '自增主键的 dataType 写 "bigint AUTO_INCREMENT"',
  sqlserver: '自增主键的 dataType 写 "bigint IDENTITY(1,1)"',
  oracle: '自增主键的 dataType 写 "NUMBER(19) GENERATED BY DEFAULT AS IDENTITY"',
  sqlite: '自增主键写 dataType "INTEGER"、单列主键即可（SQLite 的 INTEGER PRIMARY KEY 自带自增）',
  // DuckDB 没有自增列；也不收 ON DELETE 动作（schemaDraft 的校验会拦）
  duckdb: 'DuckDB 没有自增列，主键写 "bigint"，由应用给值；外键的 onDelete 一律写 null'
};

const SHAPE = `{ "tables": Array<{
    "name": string,
    "columns": Array<{ "name": string, "dataType": string, "nullable": boolean, "defaultValue": string | null }>,
    "primaryKey": string[],
    "unique": string[][],
    "indexes": Array<{ "columns": string[] }>,
    "foreignKeys": Array<{ "columns": string[], "referencedTable": string, "referencedColumns": string[], "onDelete": null | "cascade" | "set null" }>
  }> }`;

/**
 * 系统提示与用户那一段。
 *
 * 只发**结构**：库里已有的表名（让它避开重名）与当前这份设计，不发任何数据行。
 * 两条规矩来自 A0 实验（rfcs/ai-design-and-export.md §2.5）：`onDelete` 默认 null——
 * 不写时 89% 的外键是 CASCADE，「删一个用户连带删光他的订单」；以及不引用序列。
 */
export function buildDesignMessages(
  requirement: string,
  dialect: CreatableDialect,
  existingTables: readonly string[],
  current: SchemaDraft | null
): DesignMessages {
  const system = [
    `你是数据库设计助手。按需求设计 ${DIALECT_NAMES[dialect]} 的表结构，只输出一个 JSON 对象，不要任何解释或代码块标记。`,
    `JSON 结构（TypeScript 类型）：\n${SHAPE}`,
    'dataType 写该数据库的类型原文；defaultValue 写 SQL 原文（如 0、\'active\'、CURRENT_TIMESTAMP），没有就写 null。',
    '外键只能指向主键或 unique 里的列组；两端类型一致。',
    'onDelete 默认写 null（数据库拒绝删除仍被引用的行）；只有离开父行就没有意义的从属数据（订单明细、多对多关联表）才写 "cascade"；"set null" 只能用在 nullable 为 true 的列上。',
    `${AUTO_INCREMENT_HINT[dialect]}。不要引用任何序列（nextval）。`,
    '表名、列名用蛇形小写。'
  ].join('\n');

  const parts: string[] = [];
  if (existingTables.length > 0) {
    parts.push(`库里已有这些表，新表不要和它们重名；需要时可以用外键引用它们：${existingTables.join(', ')}`);
  }
  if (current) {
    parts.push(`当前的设计：\n${JSON.stringify(current)}\n\n在它的基础上修改，输出修改后的完整设计。`);
  }
  parts.push(`需求：${requirement.trim()}`);
  return { system, user: parts.join('\n\n') };
}

export type DraftParseResult =
  | { ok: true; draft: SchemaDraft }
  | { ok: false; reason: 'not-json' | 'bad-shape'; detail: string };

/**
 * 把模型的回复读成设计。
 *
 * 只容忍一种偏差：外面包了一层 ```json 代码块（Anthropic 没有 JSON 模式，常这么写）。
 * 形状不对就原样报出哪一处不对，不去补字段——补出来的设计不是模型给的那一份，
 * 而校验和人看的都该是它给的那一份。
 */
export function parseDraftResponse(text: string): DraftParseResult {
  const fenced = /```(?:json)?\s*([\s\S]*?)```/.exec(text);
  const body = (fenced?.[1] ?? text).trim();
  let value: unknown;
  try {
    value = JSON.parse(body);
  } catch (error) {
    return { ok: false, reason: 'not-json', detail: error instanceof Error ? error.message : String(error) };
  }
  const problem = shapeProblem(value);
  return problem === null
    ? { ok: true, draft: value as SchemaDraft }
    : { ok: false, reason: 'bad-shape', detail: problem };
}

const isStringArray = (value: unknown): value is string[] =>
  Array.isArray(value) && value.every((item) => typeof item === 'string');

/** 第一处不对的位置，形如 `tables[2].columns[0].nullable`；全对返回 null */
function shapeProblem(value: unknown): string | null {
  if (typeof value !== 'object' || value === null || !Array.isArray((value as { tables?: unknown }).tables)) {
    return 'tables';
  }
  const tables = (value as { tables: unknown[] }).tables;
  for (const [index, table] of tables.entries()) {
    const at = `tables[${index}]`;
    if (typeof table !== 'object' || table === null) return at;
    const record = table as Record<string, unknown>;
    if (typeof record.name !== 'string') return `${at}.name`;
    if (!Array.isArray(record.columns)) return `${at}.columns`;
    for (const [position, column] of record.columns.entries()) {
      const where = `${at}.columns[${position}]`;
      const spec = (column ?? {}) as Record<string, unknown>;
      if (typeof spec.name !== 'string') return `${where}.name`;
      if (typeof spec.dataType !== 'string') return `${where}.dataType`;
      if (typeof spec.nullable !== 'boolean') return `${where}.nullable`;
      if (spec.defaultValue !== null && typeof spec.defaultValue !== 'string') return `${where}.defaultValue`;
    }
    if (!isStringArray(record.primaryKey)) return `${at}.primaryKey`;
    if (!Array.isArray(record.unique) || !record.unique.every(isStringArray)) return `${at}.unique`;
    if (!Array.isArray(record.indexes) || !record.indexes.every((index_) => isStringArray((index_ as { columns?: unknown })?.columns))) {
      return `${at}.indexes`;
    }
    if (!Array.isArray(record.foreignKeys)) return `${at}.foreignKeys`;
    for (const [position, key] of record.foreignKeys.entries()) {
      const where = `${at}.foreignKeys[${position}]`;
      const spec = (key ?? {}) as Record<string, unknown>;
      if (!isStringArray(spec.columns)) return `${where}.columns`;
      if (typeof spec.referencedTable !== 'string') return `${where}.referencedTable`;
      if (!isStringArray(spec.referencedColumns)) return `${where}.referencedColumns`;
      if (spec.onDelete !== null && spec.onDelete !== 'cascade' && spec.onDelete !== 'set null') return `${where}.onDelete`;
    }
  }
  return null;
}
